### ISSUE TITLE
When registering a new user, add a placeholder image if no headshot is provided

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-realm#174]
This can be the image that the apps are using to denote that an avatar hasn't yet been added.

**Comment by Sheeri** [comment]
I think this would be best as a trigger - when an insert to the User table is made, if there's no photo attached, then add in a reference to a photo. This should work regardless of whether or not out-of-database photo storage is set up. 

 - If out-of-database storage is set up, ideally it would insert the photoURL, so that the same photoURL is reused over and over.
 - If out-of-database storage is NOT set up, I guess it would just insert the photo again, although that's a lot of duplication. We'll need something as small as possible. When inspecting the default image, this is what I see:

`<img class="icon profile-pic" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADsAAAA3CAIAAAA9haWfAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAjQSURBVGhD1ZkJUJTnGceBvXfZA3aXY7lv5Q4CIgY1RNFSiTamppM2tk6sR6ttmslMO5lMNJmxadRmYpPJpMk0nTbEFGfSYNskRZTUiwjhUATkBmXlWJZjYWFhL/oHXsiy++1+3wLW+pud4Xueb4H/vu/zPse3nsJNL3o8VHiRnw8PK6bY09PDy8uT5eXFZn37YuHl5enliZsrxnKjQsDjhPj7qBSS+PCA2FBlZJBCKfP2FnA5bJZhyqQ3GO8NjHTcG2zs7Gvv0d7T6Hq0OrPFSn55SSxdsUIq2pwRt+GRqORoVVSwQiLkkxtO6B8aa+keqGnuLqtquXqzY9JoJjfcZCmK+Vz2rsdSDj+1IUIlx3K6tecWi3VEb6hpVp8ovHi9octqnSY3GOOeYh6XHRui/O2hgtw1McS1VIwmy4f/uv77M19h7S1WN+KExQnPJpd0+EqE+3dkv/3CroSIAOJaBjiU6atDN2fEQnFX7zDz4GaqWCziHT+wfd8T63zEQuJaCRQy76zEMLPFUtl4l7joYKRY6eP9+akDW7NW8bkc4lohcAQkIn5uemyIn+x8RbN1mj6saRTjTCFwC4/tSYsLXtGsugj85ZRoVZCfrPxW5+SUiXidQKMYyfW1/fmb0qJRGojr/gDRyDxTRjPSn+uYptFxZHfOjpwklANi308QHs8/vWlLZhyxneB0jfGhn8lb8/qhAhRb4qIDa6PTG260qL8obyyrbm1Va7lsNhIiPjDDiOLzONvWrf6y/PbAiJ64HHCaj5OjVP849VNEBbHp0AyPnb1Qe+Z8dV1bz8LxgdYNqVHPbksvyElC3SFeOi7Xtj37aqFWN07sxVCvsbeQ99JP8rISwxmujVoz8vxbf//z55XqAR1xzYKS1tkzeOVmh3ZEvz45gmF0+fmKNSP66qZuysRBrTgrIfyXuzdKvQXEdoneMPWjYx9drGo1mS3EtRi0RNVN6imTGZWSyRLggwl53Ms32nT6SeKygSJGeRw2ginYT0ZslyB23/vs2je37067TKWow5+U1pRWNjNIuDOkrw7JjA8jxmIoFMvEgoL1CcSg407fEM4Zk0ZsYFh/7sotvYFi2RxBqXpyUwp6a2LbQKEYZyU8UE4MOtrU2lvtvcRwCerZ9foudBHEpuPx9Bilj5gYNlAofio3FdMEMVyCSEBmmJg0EpsO9Mcu0pYdIgFvZ04SMWywVyzic3NSo4hBB2JSw3jNAFKHZoipYrBzIwPFiZGBUhHNNPEt0zMnj1wzw1k+oSQjPkwk4BJjHnvF8ZFu9L7IVD4S95pPudSN96PohAf6EmMee8UxIUpyxQAkV3R2zJskVFCFjOIwuSBSpSBX89j/M7mba4b5OdSfUeYGKTFBSpmIGMzwEdtXMXvFYrqR2I6YEL/s5EgmlUzA4+Smx2DoIDYzvAU8cjUP0w11hljI27t9LZOGKS7Ub3duKvNO0Bn2vz86wagm2bIuMfzoc1sD5RJiU4HgOXl4R6BCSmzGoGkhV/PYK9aOUPd4rvlxfuZbv3pyXWKE4xKi3n53fcIHv/lBdnIEcbnD0OgEuZrHvncLC/TNz44nBmMQx9Ehyry1q+IjAsYmpvAyWSwKqejxjNiX92792a5HI4MVjKqoAyc/LkNDQoxZ7Dv6tQlhZe8cJsaDBuVGVfCKXRdgv4n1HX26cbdD+T5R0dDl2LTYKx43TF290U6MB03x5VvkygZ7xaDoQg25eqAYTRYMjsSwgWIyxYn5z7tHIlSMWuQpo7l3cLR/aLShs6+pS9OmHkC2GcOcZLLweWyJiBcgl6LyJ0QERAcrA+Rifx8xi1lK/ufV+h8e/avF4eEnhWJMTUf3bfvF9ze4rmSTRtOlmjZM+VVN3be7+ihnMluQsJFJMO1uyYhLWxVCOV8sgPA98uanRaU1jkMWxWSKmcxssWx8JNrZZIpGvrZF/cLp4j8WX7tyo6O7fxgrTe45B7UAc3VFfVdJZVNHjxZtrcR5W1vZeOfdT6+N6A3EtoF6ltYM6xMiA/FHHZcZS3vmfPX+3xXVtWP6MLkeSB3BLo+OT9Y0qzGlJkapVAqp47yDf/H+ua/PVzQRezHUitGnY+Xy1yegbSCuWTClvf6X0lc//De0EtdSGdSNF1+q85UK48L8uYufY1yvv/Pan0qcDWPUikH/8NjImCEvc9XCQcHanPq47L3icsvyvnpZwGi2YPcD5BJs5sJKY3sPnTjbqh6YMx1xemyx24UlVScKLxJ7NnwHR8fd+gaAlkmjGUd2emZinAE55uAbRVVNrp5+O11jANFNd/qDlFJsHNYAPc1jaTGj+smWbg2SJXnTMsDqvvLc1gM7s9msmahAGKCLKLpQ63p2dKUYIF5buweSolSh/j4wuRx2bnosRtf2nkHEzNx7lgAkZsaHHj+w/enNaXPxgA3EgT5ddAmxN/ceZ9AoBlqdvryuMypYERU0M3JhqsPwk5MayfL0qm1Vu5kqZpCJBS/t2fLrPZuRledykdVqPX328hsfXWTyNMPp01g7uBzWyZ/v2JOfiQvi8vBovqt58Q/nKhq7kI9pHwNw2CwRn7tzY9Lxg9tlNpkejdexD758/1w5selgqhigoBz8Xva+J9YhiRLXbENY19ZTUtF0s/Ve3+AoGnBsK5IADiiHxeJx2VJvvlwiCvaToY9FA43i72WT4+vbe9/821efXapjfjDcUAz4PA5mpH0FWd/JjkcxJ95ZcMx7BnRa3TgKlRGfwzqNeYTPZftKhJgCMS/ZjSfDY4YzJVWflNbgA7uVf9xTPAfKyqMpkS/vzUuNCSYud7Bap7/4uhFR29DZy6S827EUxXNgzVBfnslbkxobhMMkEfJdNGXYdN24AXUOfUhhyTdVt7vJDfdZuuI5oDs8UJ4crYqP8A9SSP18xch9CF/4jSYrOoThsYn+If3d/qGGjt66tl7EOpOvGV2wXMULIE8JeBwEDGIX6RZZdqYHNFtRF9AuL2H3nbFiiv9nMBoH/q942BR7ePwX3WqIxTwxOIAAAAAASUVORK5CYII=" alt="no user">`

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Placeholder image when registering a new user - Realm O-FISH](https://trello.com/c/ErJsAWqz/443-placeholder-image-when-registering-a-new-user-realm-o-fish)

**Comment by am-MongoDB** [comment]
@Sheeri we can always create a new `Photo` document that has no binary image, but does have a link to a standard image (this can be specified through a new Realm Value and we can default it to a publicly available image.

We already have the `newRealmUser` function - the functionality can be included in that (in the `linkUser` Realm Function).
